---
# Source: solr/charts/zookeeper/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: helm-solr-zookeeper
  labels:
    app: zookeeper
    chart: zookeeper-2.1.3
    release: helm-solr
    heritage: Helm
    component: server
spec:
  selector:
    matchLabels:
      app: zookeeper
      release: helm-solr
      component: server
  maxUnavailable: 1
