apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-server
  name: nexus
  namespace: nexus
spec:
  ports:
  - name: port-1
    nodePort: 30100
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: port-2
    nodePort: 30101
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nexus-server
  sessionAffinity: None
  type: NodePort