---
# nexus
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-server
  name: nexus
  namespace: nexus
spec:
  ports:
  - name: web-ui
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: docker
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: nexus-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
