# PersistentVolumeClaim - NFS
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-nexus
  namespace: devops-tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: nfs-pv-nexus