---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-0
  labels:
    app: elasticsearch
    release: elk
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    server: 10.8.41.12
    path: /mnt/sharedfolder/gwdc/elasticstack/elasticsearch/0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-1
  labels:
    app: elasticsearch
    release: elk
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    server: 10.8.41.12
    path: /mnt/sharedfolder/gwdc/elasticstack/elasticsearch/1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-logstash-0
  labels:
    app: logstash
    release: elk
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  nfs:
    server: 10.8.41.12
    path: /mnt/sharedfolder/gwdc/elasticstack/logstash/0
...