apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/instance: nexus
    volume: phabricator-data
  name: phabricator-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nexus
    namespace: nexus
  nfs:
    path: /mnt/sharedfolder/gwdc/phabricator/data
    server: 10.8.41.12
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem