---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-home
  labels:
    volume: jenkins-master-home
    app.kubernetes.io/instance: jenkins
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  nfs:
    server: 10.8.41.12
    path: /mnt/sharedfolder/gwdc/jenkins/master