---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: jenkins
  name: secrets-integrator-jenkins
  namespace: jenkins
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-inject-secret-app.json: "jenkins/kv/app"
            vault.hashicorp.com/agent-inject-template-app.json: |
              {{- with secret "jenkins/kv/app" -}}
              {
                "apiVersion": "v1",
                "kind": "Secret",
                "metadata": {
                  "name": "stable-jenkins-2-1-0"
                },
                "type": "Opaque",
                "stringData": {
                {{ range $k, $v := .Data.data }}
                "{{ $k }}": "{{ $v }}",
                {{ end }}
                "end": "NULL"
                }
              }
              {{- end }}
            vault.hashicorp.com/role: "jenkins"
        spec:
          containers:
            - name: jenkins-vault-kube-integrator
              image: "bitnami/kubectl:1.17.4"
              imagePullPolicy: "IfNotPresent"
              command:
                - kubectl
                - apply
                - "-f"
                - /vault/secrets/
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: stable-jenkins-2-1-0
...