version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - './data/mariadb:/bitnami'

  phabricator:
    image: 'bitnami/phabricator:2020'
    environment:
    - PHABRICATOR_HOST=www.example.com
    - PHABRICATOR_USERNAME=user
    - PHABRICATOR_PASSWORD=bitnami1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './data/phabricator:/bitnami'
    depends_on:
      - mariadb
    hostname: www.example.com
  
  ldap:
    container_name: ldap
    environment:
      LDAP_TLS: 'true'
      LDAP_TLS_CRT_FILENAME: 'fullchain.pem'
      LDAP_TLS_KEY_FILENAME: 'privkey.pem'
      LDAP_TLS_CA_CRT_FILENAME: 'fullchain.pem'
      LDAP_ORGANISATION: "TemplateLdap"
      LDAP_DOMAIN: "ldap"
      LDAP_BASE_DN: "dc=ldap"
      LDAP_ADMIN_PASSWORD: "test"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_TLS_VERIFY_CLIENT: "allow"
    hostname: ldap
    image: osixia/openldap:stable-amd64
    ports:
    - "389"
    - "636"
    tty: true
    volumes:
    - ./data/ldap:/etc/ldap/slapd.d
    - ./data/slapd/database:/var/lib/ldap
