---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-server
  namespace: gwcloud
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: solr
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    server: 10.8.41.12
    path: /mnt/sharedfolder/gwdc/solr/server
