---
# Source: solr/charts/zookeeper/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: solr-helm-zookeeper
  labels:
    app: zookeeper
    chart: zookeeper-2.1.3
    release: solr-helm
    heritage: Helm
    component: server
spec:
  selector:
    matchLabels:
      app: zookeeper
      release: solr-helm
      component: server
  maxUnavailable: 1
