---
# Source: solr/charts/zookeeper/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: incubator-1-5-2-zookeeper
  labels:
    app: zookeeper
    chart: zookeeper-2.1.3
    release: incubator-1-5-2
    heritage: Helm
    component: server
spec:
  selector:
    matchLabels:
      app: zookeeper
      release: incubator-1-5-2
      component: server
  maxUnavailable: 1
