---
# Source: solr/charts/zookeeper/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: solr-helm-zookeeper
  labels:
    app: zookeeper
    chart: zookeeper-2.1.3
    release: solr-helm
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
  selector:
    app: zookeeper
    release: solr-helm
