---
# Source: vault/templates/server-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: may0620-vault
  namespace: vault
  labels:
    helm.sh/chart: vault-0.5.0
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: may0620
    app.kubernetes.io/managed-by: Helm
