---
# PersistentVolume - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus
  labels:
    volume: nexus
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 10.8.0.37
    path: "/mnt/sharedfolder/gwdc/nexus_data"
