---
# Source: solr/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr-helm
  labels:
    app.kubernetes.io/name: solr
    app.kubernetes.io/instance: solr-helm
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: solr-1.5.2
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "solr"
      app.kubernetes.io/instance: "solr-helm"
      app.kubernetes.io/component: "server"
  serviceName: solr-helm-headless
  replicas: 1
  updateStrategy:
        type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "solr"
        app.kubernetes.io/instance: "solr-helm"
        app.kubernetes.io/component: "server"
      annotations:
        {}
    spec:      
      securityContext:
        fsGroup: 8983
        runAsUser: 8983
      affinity:
        {}
      tolerations:
        []
      terminationGracePeriodSeconds: 180
      volumes:
        - name: solr-xml
          configMap:
            name: solr-helm-config-map
            items:
              - key: solr.xml
                path: solr.xml
      initContainers:
        - name: check-zk
          image: busybox:latest
          command:
            - 'sh'
            - '-c'
            - |
              COUNTER=0;
              while [  $COUNTER -lt 120 ]; do
                addr=$(nslookup -type=a solr-helm-zookeeper-headless | grep "Address:" | awk 'NR>1 {print $2}')
                if [ ! -z "$addr" ]; then
                  while read -r line; do
                    echo $line;
                    mode=$(echo srvr | nc $line 2181 | grep "Mode");
                    echo $mode;
                    if [ "$mode" = "Mode: leader" ] || [ "$mode" = "Mode: standalone" ]; then
                      echo "Found a leader!";
                      exit 0;
                    fi;
                  done <<EOF
              $addr
              EOF
                fi;
                let COUNTER=COUNTER+1;
                sleep 2;
              done;
              echo "Did NOT see a ZK leader after 240 secs!";
              exit 1;
        - name: "cp-solr-xml"
          image: busybox:latest
          command: ['sh', '-c', 'cp /tmp/solr.xml /tmp-config/solr.xml']
          volumeMounts:
            - name: "solr-xml"
              mountPath: "/tmp"
            - name: "solr-helm-pvc"
              mountPath: "/tmp-config"
      containers:
        - name: solr
          image: "solr:8.4.0"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          ports:
            - containerPort: 8983
              name: solr-client
          env:
            - name: "SOLR_JAVA_MEM"
              value: "-Xms512m -Xmx1g"
            - name: "SOLR_HOME"
              value: "/opt/solr/server/home"
            - name: "SOLR_PORT"
              value: "8983"
            - name: "POD_HOSTNAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "SOLR_HOST"
              value: "$(POD_HOSTNAME).solr-helm-headless.solr"
            - name: "ZK_HOST"
              value: "solr-helm-zookeeper-headless:2181"
            - name: "SOLR_LOG_LEVEL"
              value: "INFO"

          livenessProbe:
            initialDelaySeconds: 45
            periodSeconds: 10
            httpGet:
              scheme: "HTTP"
              path: /solr/admin/info/system
              port: 8983
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            httpGet:
              scheme: "HTTP"
              path: /solr/admin/info/system
              port: 8983
          volumeMounts:
            - name: solr-helm-pvc
              mountPath: /opt/solr/server/home

  volumeClaimTemplates:
    - metadata:
        name: solr-helm-pvc
        annotations:
          pv.beta.kubernetes.io/gid: "8983"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
