---
# Source: mysqldump/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-mysqldump-2-6-0
  labels:
    app.kubernetes.io/name: mysqldump
    helm.sh/chart: mysqldump-2.6.0
    app.kubernetes.io/instance: stable-mysqldump-2-6-0
    app.kubernetes.io/version: "2.4.1"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
---
# Source: mysqldump/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdiff-backup-0-1-0
  labels:
    app.kubernetes.io/name: rdiff-backup
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
