---
# Source: phabricator/charts/mariadb/templates/master-configmap.yaml
apiVersion: v1
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
kind: ConfigMap
metadata:
  labels:
    app: mariadb
    app.kubernetes.io/instance: phabricator
    chart: mariadb-7.3.16
    component: master
    heritage: Tiller
    release: phabricator
  name: phabricator-mariadb-master
  namespace: phabricator
---
apiVersion: v1
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
kind: ConfigMap
metadata:
  labels:
    app: mariadb
    app.kubernetes.io/instance: phabricator
    chart: mariadb-7.3.16
    component: slave
    heritage: Tiller
    release: phabricator
  name: phabricator-mariadb-slave
  namespace: phabricator
---
apiVersion: v1
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h phabricator-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: phabricator
  name: phabricator-mariadb-tests
  namespace: phabricator