apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
      app: mariadb
      component: master
      release: phabricator
  name: phabricator-mariadb-master
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  nfs:
    path: /mnt/sharedfolder/gwdc/phabricator/mariadb/master
    server: 10.8.41.12
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    app: mariadb
    component: slave
    release: phabricator
  name: phabricator-mariadb-slave
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  nfs:
    path: /mnt/sharedfolder/gwdc/phabricator/mariadb/slave
    server: 10.8.41.12
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem