kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: phabricator
  namespace: phabricator
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      volume: phabricator
