---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-integrator-phabricator
  namespace: phabricator
  labels:
    app: vault-agent
spec:
  selector:
    matchLabels:
      app: vault-kube-integrator
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-secret-app: "phabricator/kv/app"
        vault.hashicorp.com/agent-inject-template-app: |
          {{- with secret "phabricator/kv" -}}
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: phabricator-app
          type: Opaque
          stringData:
            {{ range $k, $v := .Data.data }}
            {{ $k }}: {{ $v }}
            {{ end }}
          ...
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-db-master: "phabricator/kv/db-master"
        vault.hashicorp.com/agent-inject-template-db-master: |
          {{- with secret "phabricator/kv/db-master" -}}
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: phabricator-db-master
          type: Opaque
          stringData:
            {{ range $k, $v := .Data.data }}
            {{ $k }}: {{ $v }}
            {{ end }}
          ...
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-db-replica: "phabricator/kv/db-replica"
        vault.hashicorp.com/agent-inject-template-db-replica: |
          {{- with secret "phabricator/kv/db-replica" -}}
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: phabricator-db-replica
          type: Opaque
          stringData:
            {{ range $k, $v := .Data.data }}
            {{ $k }}: {{ $v }}
            {{ end }}
          ...
          {{- end }}
        vault.hashicorp.com/role: "phabricator"
      labels:
        app: vault-kube-integrator
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      serviceAccountName: phabricator
      containers:
      - name: app
        image: bitnami/kubectl:1.17.4
        command: ["bash"]
        livenessProbe:
          exec:
            command:
            - kubectl
            - apply 
            - -f
            - /vault/secrets/
          initialDelaySeconds: 5
          periodSeconds: 5
        tty: true
        volumeMounts:
          - mountPath: /.kube
            name: secrets
      nodeSelector:
        dedicated: master
      volumes:
        - name: secrets
          hostPath:
            path: /home/ubuntu/.kube
            type: Directory
...