---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: phabricator
  name: secrets-integrator-phabricator
  namespace: phabricator
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-inject-secret-app.json: "phabricator/kv/app"
            vault.hashicorp.com/agent-inject-template-app.json: |
              {{- with secret "phabricator/kv/app" -}}
              {
                "apiVersion": "v1",
                "kind": "Secret",
                "metadata": {
                  "name": "phabricator-app"
                },
                "type": "Opaque",
                "stringData": {
                {{ range $k, $v := .Data.data }}
                "{{ $k }}": "{{ $v }}",
                {{ end }}
                "end": "NULL"
                }
              }
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-db-master.json: "phabricator/kv/db-master"
            vault.hashicorp.com/agent-inject-template-db-master.json: |
              {{- with secret "phabricator/kv/db-master" -}}
              {
                "apiVersion": "v1",
                "kind": "Secret",
                "metadata": {
                  "name": "phabricator-db-master"
                },
                "type": "Opaque",
                "stringData": {
                {{ range $k, $v := .Data.data }}
                "{{ $k }}": "{{ $v }}",
                {{ end }}
                "end": "NULL"
                }
              }
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-db-replica.json: "phabricator/kv/db-replica"
            vault.hashicorp.com/agent-inject-template-db-replica.json: |
              {{- with secret "phabricator/kv/db-replica" -}}
              {
                "apiVersion": "v1",
                "kind": "Secret",
                "metadata": {
                  "name": "phabricator-db-replica"
                },
                "type": "Opaque",
                "stringData": {
                {{ range $k, $v := .Data.data }}
                "{{ $k }}": "{{ $v }}",
                {{ end }}
                "end": "NULL"
                }
              }
              {{- end }}
            vault.hashicorp.com/role: "phabricator"
          labels:
            app: vault-kube-integrator
        spec:
          containers:
            - name: phabricator-vault-kube-integrator
              image: "bitnami/kubectl:1.17.4"
              imagePullPolicy: "IfNotPresent"
              command:
                - kubectl
                - apply
                - "-f"
                - /vault/secrets/
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: phabricator
...