---
# Source: phabricator/templates/secrets.yaml
apiVersion: v1
data:
  phabricator-password: N3J3cVMwa1BXcg==
  smtp-password: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: phabricator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: phabricator
    helm.sh/chart: phabricator-9.0.17
  name: phabricator
  namespace: phabricator
type: Opaque