apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: phabricator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: phabricator
    helm.sh/chart: phabricator-9.0.17
  name: phabricator
  namespace: phabricator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi