---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup
  labels:
    app: backup
data:
  backup.sh: |-
    #!/bin/bash
    if [[ -z "$SOURCE" ] && [ -z "$BACKUP" ]]
    then
      # TEST COMMANDS
      df -h $SOURCE;
      df -h $BACKUP;
      # cp -vrfp $SOURCE $BACKUP;
    else
      echo "ENV vars SOURCE or BACKUP are not initialised";
    fi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mounts
  labels:
    app: backup
data:
  SOURCE: /nfs1
  BACKUP: /nfs2