---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup
  labels:
    app: backup
data:
  backup.sh: |-
    #!/bin/sh
    if [ -z "$SOURCE" ] && [ -z "$BACKUP" ]
    then
      echo "ENV vars SOURCE or BACKUP are not initialised";
    else
      # rdiff-backup
      rdiff-backup --print-statistics --force --exclude ${SOURCE}/gwdc/vault/data/sys/expire --exclude ${SOURCE}/gwdc/vault/data/sys/token $SOURCE $BACKUP;
      df -h $SOURCE;
      df -h $BACKUP;
    fi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mounts
  labels:
    app: backup
data:
  SOURCE: /nfs1
  BACKUP: /nfs2
