---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
  labels:
    app: nfs1
spec:
  capacity:
    storage: 1000Gi
  claimRef:
     namespace: backup
     name: nfs
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/
    server: nfs1.private.loc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs2
  labels:
    app: nfs
spec:
  capacity:
    storage: 1000Gi
  claimRef:
     namespace: backup
     name: nfs2
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/
    server: nfs2.private.loc