---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs1
  labels:
    app: nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs2
  labels:
    app: nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi