
---
# Ingress
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: weave-scope
  namespace: weave
spec:
  host: weave.gw-cloud.org
  upstreams:
    - name: weave-scope-app
      service: weave-scope-app
      port: 80
  routes:
    - path: / 
      action:
        pass: weave-scope-app
...