---
# PersistentVolume - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nexus
  labels:
    volume: nfs-pv-nexus
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: 10.8.0.37
    path: "/mnt/sharedfolder/gwdc/nexus_data"
---
# PersistentVolumeClaim - NFS
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-nexus
  namespace: devops-tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: nfs-pv-nexus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: devops-tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "4000m"
            requests:
              memory: "2Gi"
              cpu: "100m"
          ports:
            - containerPort: 8081
            - containerPort: 9001
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nfs-pvc-nexus
      restartPolicy: Always
---
# Nexus
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: devops-tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "4000m"
            requests:
              memory: "2Gi"
              cpu: "100m"
          ports:
            - containerPort: 8081
            - containerPort: 9001
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nfs-pvc-nexus
      restartPolicy: Always
---
# nexus http, docker
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-server
  name: nexus-web
  namespace: devops-tools
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30100
    name: web-ui
    port: 8081
    protocol: TCP
    targetPort: 8081
  - nodePort: 30101
    name: http-docker
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: nexus-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
