---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-integrator-common
  namespace: gwcloud
  labels:
    app: vault-agent
spec:
  selector:
    matchLabels:
      app: vault-kube-integrator
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-secret-common.yaml: "kv/gwcloud/common"
        vault.hashicorp.com/agent-inject-template-common.yaml: |
          {{- with secret "kv/gwcloud/common" -}}
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: common
          type: Opaque
          stringData:
            {{ range $k, $v := .Data }}
            {{ $k }}: {{ $v }}
            {{ end }}
          ...
          {{- end }}
        vault.hashicorp.com/role: "common"
      labels:
        app: vault-kube-integrator
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      serviceAccountName: gwcloud
      containers:
      - name: app
        image: bitnami/kubectl:1.17.4
        command: ["bash"]
        livenessProbe:
          exec:
            command:
            - kubectl
            - apply 
            - -f
            - /vault/secrets
          initialDelaySeconds: 5
          periodSeconds: 5
        tty: true
        resources: {}
