---
apiVersion: batch/v1
kind: Job
metadata:
  name: react-host
  namespace: gwcloud
  labels:
    app: vault-agent
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-secret-env: "gwcloud/kv/react-host"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "gwcloud/kv/react-host" -}}
           ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: react-host
          type: Opaque
          stringData:
            {{ range $k, $v := .Data }}
              {{ $k }}: {{ $v }}
            {{ end }}
          ...
          {{- end }}
        vault.hashicorp.com/role: "gwcloud"
      labels:
        app: vault-agent
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      serviceAccountName: gwcloud
      containers:
      - name: app
        image: bitnami/kubectl:1.17.4
        args: [
        "apply","-f","/vault/secrets/env"
        ]
        volumeMounts:
          - mountPath: /.kube
            name: secrets
      nodeSelector:
        dedicated: master
      volumes:
        - name: secrets
          hostPath:
            path: /home/ubuntu/.kube
            type: Directory
...