# PersistentVolumeClaim - NFS
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus
  namespace: nexus
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: nexus